services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
#    networks:
#      - ecomm-network
#    restart: unless-stopped
#
#networks:
#  ecomm-network:
#
#volumes:
#  postgres_data:
