services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - ecomm-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
        ME_CONFIG_MONGODB_SERVER: mongodb
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8090:8081"
    networks:
      - ecomm-network

networks:
  ecomm-network:

#volumes:
#  postgres_data:
